package fr.epita.dto.Request;

import fr.epita.enums.StudentStatus;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
public class CreateStudentRequest {

    @NotBlank(message = "First name is required")
    private String firstName;

    @NotBlank(message = "Last name is required")
    private String lastName;

    // Platform email is auto-generated server-side (firstname.lastname@domain).
    // Still accepted here so the update path can optionally supply an override.
    @Email(message = "Must be a valid email address")
    private String email;

    // Personal email — where login credentials are sent on first creation.
    @Email(message = "Must be a valid personal email address")
    private String personalEmail;

    // One-time password is generated by the server and emailed to the student.
    private String password;

    @NotBlank(message = "Student reference is required")
    private String studentRef;

    @NotNull(message = "Programme ID is required")
    private Long programmeId;

    @NotNull(message = "Status is required")
    private StudentStatus status;

    @NotNull(message = "Cohort ID is required")
    private Long cohortId;
}


