# DataSource Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/actionlearning
spring.datasource.username=postgres
spring.datasource.password=passworddb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security Configuration
spring.security.user.name=actionlearning
spring.security.user.password=123456789